### ISSUE TITLE
Should *int(1) be mapped to boolean type?

### ISSUE THREAD

**Issue by rexxars** [vaffel/sql-to-graphql#5]
Should we assume that `int(1)`, `tinyint(1)` etc are meant to be booleans, and map them as such?

The "problem" here is that an `tinyint(1)` can actually still store 255 different values, so it might be an incorrect assumption. Perhaps a CLI-flag?

**Comment by rexxars** [comment]
Maybe it would be a good idea to run something similar to:
`SELECT 1 FROM FROM tableName WHERE tinyintColumn NOT IN(0, 1) LIMIT 1 `. If there are any values that are not 0/1, we can keep it as an integer, otherwise treat it as a boolean?

**Comment by jonny827** [comment]
I have been following this project for some time. I have not written any GraphQL by hand and was hoping to use your tool.  I would like to provide feedback for this if I may since i do have quite a bit of research and thought put into this from another thread through the Doctrine ORM project. They recently moved their JIRA over to Gitbub  issues/pull requests so check out - https://github.com/doctrine/dbal/issues/1205 .   

1. Do not assume int(1) or tinyint(1) are booleans.  First int(1) still stores the ENTIRE value of INT(all 11 digits) it however only send the 1st back in the result set. Meaning from my understanding the value in (1) is only a display length value not a store length value.  Secondly, Tinyint(1) as in my article can be used to store up to 255 values if unsigned.  Map boolean only to explicit boolean.

2. These above approaches require database developers to be more thorough in their design, and declarative in their field types, and still give your tool the power of flexibility because you are not typing a develop into having to hack his design for example tinyint(2) if for example he is trying to store the value "7" as in the days of the week enum in order to prevent your script from trying to force a boolean value.

Keep up the solid work on this project as your project will save developers hundreds of hours of tedious writing of schemas and get them back to write functionality.

**Comment by rexxars** [comment]
Thanks for the feedback, I agree with your conclusions. Closing this.
